"""init table

Revision ID: 03137a3a56ba
Revises: a78cf029de22
Create Date: 2026-03-20 15:38:52.424069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03137a3a56ba'
down_revision: Union[str, Sequence[str], None] = 'a78cf029de22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置ID'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='配置编码'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='配置值'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='配置排序,越大越靠前'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='配置表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_configs')
    # ### end Alembic commands ###
