"""init table

Revision ID: 1a7edf0c7146
Revises: f000aba9d679
Create Date: 2026-03-09 13:25:24.684502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7edf0c7146'
down_revision: Union[str, Sequence[str], None] = 'f000aba9d679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='登录邮箱'),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级用户'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='是否验证'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False, comment='登录邮箱'),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否超级用户'),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否验证'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_table('sys_users')
    # ### end Alembic commands ###
