"""init table

Revision ID: c1051e123a63
Revises: de9b00597988
Create Date: 2026-03-11 09:25:52.879508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1051e123a63'
down_revision: Union[str, Sequence[str], None] = 'de9b00597988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menus', sa.Column('permission', sa.String(length=100), nullable=True, comment='菜单权限, NULL:目录'))
    op.add_column('sys_menus', sa.Column('type', sa.Integer(), nullable=False, comment='菜单类型, 1:目录, 2:页面, 3:按钮'))
    op.add_column('sys_menus', sa.Column('action_type', sa.Integer(), nullable=True, comment='操作类型, NULL:页面/目录 1:批量按钮 2:行按钮 3:工具栏按钮'))
    op.add_column('sys_menus', sa.Column('sort', sa.Integer(), nullable=False, comment='菜单排序, 越大越靠前'))
    op.add_column('sys_menus', sa.Column('visible', sa.Boolean(), nullable=False, comment='是否可见'))
    op.alter_column('sys_menus', 'path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='菜单路径')
    op.alter_column('sys_menus', 'icon',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='菜单图标')
    op.drop_column('sys_menus', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menus', sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='菜单编码'))
    op.alter_column('sys_menus', 'icon',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='菜单图标')
    op.alter_column('sys_menus', 'path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='菜单路径')
    op.drop_column('sys_menus', 'visible')
    op.drop_column('sys_menus', 'sort')
    op.drop_column('sys_menus', 'action_type')
    op.drop_column('sys_menus', 'type')
    op.drop_column('sys_menus', 'permission')
    # ### end Alembic commands ###
