"""init table

Revision ID: de9b00597988
Revises: 4503f7ef7bc0
Create Date: 2026-03-09 15:31:01.516890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9b00597988'
down_revision: Union[str, Sequence[str], None] = '4503f7ef7bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='菜单ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='菜单名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='菜单编码'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='菜单路径'),
    sa.Column('icon', sa.String(length=100), nullable=False, comment='菜单图标'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menus.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表'
    )
    op.create_table('sys_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_table('sys_role_menus',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单ID'),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menus.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    comment='角色菜单表'
    )
    op.create_foreign_key(None, 'sys_user_roles', 'sys_users', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'sys_user_roles', 'sys_roles', ['role_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'sys_user_roles', type_='foreignkey')
    op.drop_table('sys_role_menus')
    op.drop_table('sys_roles')
    op.drop_table('sys_menus')
    # ### end Alembic commands ###
