"""init table

Revision ID: f000aba9d679
Revises: 429c324f2189
Create Date: 2026-03-09 13:22:09.736381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f000aba9d679'
down_revision: Union[str, Sequence[str], None] = '429c324f2189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='登录邮箱'),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级用户'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='是否验证'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
